# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
import tensorflow as tf
from pathlib import Path
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Upload credit_card_transactions.csv to Colab
#from google.colab import files

#csv_file = files.upload()

In [3]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(Path('Resources/applicants_data.csv'))

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [5]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(["EIN","NAME"], axis=1)
# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [6]:
# Create a list of categorical variables 
categorical_variables = ['APPLICATION_TYPE','AFFILIATION','CLASSIFICATION','USE_CASE','ORGANIZATION','STATUS','SPECIAL_CONSIDERATIONS']

# Display the categorical variables list
print(categorical_variables)

['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'STATUS', 'SPECIAL_CONSIDERATIONS']

In [7]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [8]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])
encoded_data

array([[1., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [9]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data, columns=enc.get_feature_names_out(categorical_variables))

# Review the DataFrame
encoded_df

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,STATUS_0,STATUS_1,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [10]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
applicant_data_df=applicant_data_df[['IS_SUCCESSFUL']]
encoded_df1 = pd.concat([encoded_df,applicant_data_df],axis=1)

# Review the Dataframe
encoded_df1

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,STATUS_0,STATUS_1,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [11]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df1["IS_SUCCESSFUL"]

# Display a sample of y
y

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [12]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df1.drop('IS_SUCCESSFUL', axis=1)

# Review the features DataFrame
X

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,STATUS_0,STATUS_1,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [13]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [14]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X)

# Fit the scaler to the features training dataset
X_train_scaled = scaler.fit(X_train)
X_test_scaled = scaler.fit(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [15]:
# Define the the number of inputs (features) to the model
number_input_features = 107

# Review the number of features
number_input_features

107

In [16]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [17]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  10

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

10

In [18]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  10
# Review the number hidden nodes in the second layer
hidden_nodes_layer2

10

In [19]:
# Create the Sequential model instance
nn = Sequential()

In [20]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1,input_dim=number_input_features,activation="relu"))

In [21]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2,activation="relu"))

In [22]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons,activation="linear"))

In [23]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 10)                1080

 dense_1 (Dense)             (None, 10)                110

 dense_2 (Dense)             (None, 1)                 11

=================================================================
Total params: 1,201
Trainable params: 1,201
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [24]:
# Compile the Sequential model
nn.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])

In [25]:
# Fit the model using 50 epochs and the training data
model=nn.fit(X,y,validation_split=0.25,epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 1ms/step - loss: 0.5900 - accuracy: 0.7079 - val_loss: 0.6002 - val_accuracy: 0.6877
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5646 - accuracy: 0.7248 - val_loss: 0.6036 - val_accuracy: 0.6877
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5523 - accuracy: 0.7335 - val_loss: 0.5986 - val_accuracy: 0.6877
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5498 - accuracy: 0.7329 - val_loss: 0.5961 - val_accuracy: 0.6868
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5520 - accuracy: 0.7353 - val_loss: 0.6034 - val_accuracy: 0.6899
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5504 - accuracy: 0.7355 - val_loss: 0.6031 - val_accuracy: 0.6911
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5494 - accuracy: 0.7356 - val_loss: 0.6060 - val_accuracy: 0.6864
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7371 - val_loss: 0.6000 - val_accuracy: 0.6913
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5465 - accuracy: 0.7366 - val_loss: 0.5965 - val_accuracy: 0.6922
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7371 - val_loss: 0.6060 - val_accuracy: 0.6908
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5576 - accuracy: 0.7230 - val_loss: 0.6506 - val_accuracy: 0.5721
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5516 - accuracy: 0.7325 - val_loss: 0.5988 - val_accuracy: 0.6907
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7373 - val_loss: 0.6018 - val_accuracy: 0.6911
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5452 - accuracy: 0.7381 - val_loss: 0.6115 - val_accuracy: 0.6630
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5449 - accuracy: 0.7376 - val_loss: 0.6128 - val_accuracy: 0.6907
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5454 - accuracy: 0.7368 - val_loss: 0.6051 - val_accuracy: 0.6907
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5514 - accuracy: 0.7377 - val_loss: 0.6092 - val_accuracy: 0.6920
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5469 - accuracy: 0.7367 - val_loss: 0.6091 - val_accuracy: 0.6912
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5457 - accuracy: 0.7381 - val_loss: 0.6065 - val_accuracy: 0.6911
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5516 - accuracy: 0.7325 - val_loss: 0.6116 - val_accuracy: 0.6900
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5467 - accuracy: 0.7332 - val_loss: 0.6067 - val_accuracy: 0.6805
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5457 - accuracy: 0.7359 - val_loss: 0.6149 - val_accuracy: 0.6834
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5461 - accuracy: 0.7358 - val_loss: 0.6028 - val_accuracy: 0.6887
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7379 - val_loss: 0.6236 - val_accuracy: 0.6908
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7384 - val_loss: 0.6049 - val_accuracy: 0.6899
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5492 - accuracy: 0.7372 - val_loss: 0.6079 - val_accuracy: 0.6914
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5462 - accuracy: 0.7370 - val_loss: 0.6071 - val_accuracy: 0.6892
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7380 - val_loss: 0.6177 - val_accuracy: 0.6893
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7387 - val_loss: 0.6069 - val_accuracy: 0.6878
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7389 - val_loss: 0.6149 - val_accuracy: 0.6887
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7387 - val_loss: 0.6125 - val_accuracy: 0.6893
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7382 - val_loss: 0.6111 - val_accuracy: 0.6896
Epoch 33/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7373 - val_loss: 0.6097 - val_accuracy: 0.6904
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7369 - val_loss: 0.6078 - val_accuracy: 0.6907
Epoch 35/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7375 - val_loss: 0.6193 - val_accuracy: 0.6814
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7376 - val_loss: 0.6082 - val_accuracy: 0.6953
Epoch 37/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5446 - accuracy: 0.7387 - val_loss: 0.6112 - val_accuracy: 0.6912
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7377 - val_loss: 0.6107 - val_accuracy: 0.6934
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7383 - val_loss: 0.6088 - val_accuracy: 0.6848
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5483 - accuracy: 0.7339 - val_loss: 0.6058 - val_accuracy: 0.6932
Epoch 41/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7381 - val_loss: 0.6084 - val_accuracy: 0.6941
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7374 - val_loss: 0.6060 - val_accuracy: 0.6887
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7385 - val_loss: 0.6075 - val_accuracy: 0.6889
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7389 - val_loss: 0.6090 - val_accuracy: 0.6897
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5454 - accuracy: 0.7390 - val_loss: 0.6187 - val_accuracy: 0.6807
Epoch 46/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7381 - val_loss: 0.6159 - val_accuracy: 0.6919
Epoch 47/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7386 - val_loss: 0.6140 - val_accuracy: 0.6915
Epoch 48/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5508 - accuracy: 0.7385 - val_loss: 0.6104 - val_accuracy: 0.6914
Epoch 49/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7389 - val_loss: 0.6157 - val_accuracy: 0.6924
Epoch 50/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7384 - val_loss: 0.6085 - val_accuracy: 0.6894

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [26]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X,y)
# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

1072/1072 [==============================] - 1s 794us/step - loss: 0.5581 - accuracy: 0.7273
Loss: 0.5581243634223938, Accuracy: 0.727338969707489

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [27]:
# Set the model's file path
file_path = Path("Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

In [28]:
X_train

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,STATUS_0,STATUS_1,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
10679,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
5052,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
9990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
25173,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
11405,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7813,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
32511,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
5192,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
12172,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
33003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

### Alternative Model 1

In [29]:
#Drop some of the features 
X=X.drop(columns=['APPLICATION_TYPE_T19','APPLICATION_TYPE_T3','APPLICATION_TYPE_T4','APPLICATION_TYPE_T5','APPLICATION_TYPE_T6','APPLICATION_TYPE_T7'])

In [30]:
X_train

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,STATUS_0,STATUS_1,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
10679,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
5052,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
9990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
25173,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
11405,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7813,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
32511,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
5192,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
12172,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
33003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

#### Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

In [31]:
number_input_features = len(X.iloc[0])
print(number_input_features)

101

In [32]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 2

In [33]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 15

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

15

In [34]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [35]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation='relu'))


# Output layer
nn_A1.add(Dense(units=number_output_neurons_A1,activation='linear'))


# Check the structure of the model
# YOUR CODE HERE

In [36]:
# Compile the Sequential model
nn_A1.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])

In [37]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X,y,validation_split=0.3, epochs=50)

Epoch 1/50
751/751 [==============================] - 2s 2ms/step - loss: 0.9342 - accuracy: 0.5882 - val_loss: 0.6495 - val_accuracy: 0.5690
Epoch 2/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5790 - accuracy: 0.5452 - val_loss: 0.6431 - val_accuracy: 0.5692
Epoch 3/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5695 - accuracy: 0.5492 - val_loss: 0.6431 - val_accuracy: 0.5107
Epoch 4/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5667 - accuracy: 0.5375 - val_loss: 0.6432 - val_accuracy: 0.5511
Epoch 5/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5677 - accuracy: 0.5104 - val_loss: 0.6450 - val_accuracy: 0.4652
Epoch 6/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5621 - accuracy: 0.5062 - val_loss: 0.6456 - val_accuracy: 0.5761
Epoch 7/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5642 - accuracy: 0.5208 - val_loss: 0.6470 - val_accuracy: 0.6034
Epoch 8/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5983 - accuracy: 0.5128 - val_loss: 0.7077 - val_accuracy: 0.5807
Epoch 9/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5675 - accuracy: 0.4340 - val_loss: 0.6436 - val_accuracy: 0.4199
Epoch 10/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5604 - accuracy: 0.4318 - val_loss: 0.6501 - val_accuracy: 0.3874
Epoch 11/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5602 - accuracy: 0.4360 - val_loss: 0.6511 - val_accuracy: 0.4525
Epoch 12/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5593 - accuracy: 0.4439 - val_loss: 0.6491 - val_accuracy: 0.5108
Epoch 13/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5592 - accuracy: 0.4690 - val_loss: 0.6494 - val_accuracy: 0.4122
Epoch 14/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5643 - accuracy: 0.5129 - val_loss: 0.6480 - val_accuracy: 0.5933
Epoch 15/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5608 - accuracy: 0.5357 - val_loss: 0.6489 - val_accuracy: 0.5079
Epoch 16/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5583 - accuracy: 0.5109 - val_loss: 0.6663 - val_accuracy: 0.5123
Epoch 17/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5586 - accuracy: 0.4977 - val_loss: 0.6536 - val_accuracy: 0.5022
Epoch 18/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5581 - accuracy: 0.4942 - val_loss: 0.6463 - val_accuracy: 0.6179
Epoch 19/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5575 - accuracy: 0.4947 - val_loss: 0.6716 - val_accuracy: 0.5744
Epoch 20/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.4932 - val_loss: 0.6535 - val_accuracy: 0.6297
Epoch 21/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5594 - accuracy: 0.4889 - val_loss: 0.6507 - val_accuracy: 0.5326
Epoch 22/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5567 - accuracy: 0.5156 - val_loss: 0.6510 - val_accuracy: 0.5630
Epoch 23/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5614 - accuracy: 0.4711 - val_loss: 0.6479 - val_accuracy: 0.4866
Epoch 24/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5577 - accuracy: 0.5124 - val_loss: 0.6449 - val_accuracy: 0.4357
Epoch 25/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5564 - accuracy: 0.4866 - val_loss: 0.6497 - val_accuracy: 0.4371
Epoch 26/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5569 - accuracy: 0.5060 - val_loss: 0.6507 - val_accuracy: 0.5778
Epoch 27/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.4825 - val_loss: 0.6500 - val_accuracy: 0.4439
Epoch 28/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5571 - accuracy: 0.5142 - val_loss: 0.6521 - val_accuracy: 0.4320
Epoch 29/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5572 - accuracy: 0.4908 - val_loss: 0.6450 - val_accuracy: 0.5308
Epoch 30/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.4979 - val_loss: 0.6460 - val_accuracy: 0.4193
Epoch 31/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5563 - accuracy: 0.5011 - val_loss: 0.6512 - val_accuracy: 0.5040
Epoch 32/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5567 - accuracy: 0.5043 - val_loss: 0.6451 - val_accuracy: 0.4583
Epoch 33/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.4994 - val_loss: 0.6454 - val_accuracy: 0.4688
Epoch 34/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5562 - accuracy: 0.4790 - val_loss: 0.6515 - val_accuracy: 0.4437
Epoch 35/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5561 - accuracy: 0.5091 - val_loss: 0.6592 - val_accuracy: 0.5693
Epoch 36/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.4989 - val_loss: 0.6441 - val_accuracy: 0.4894
Epoch 37/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5606 - accuracy: 0.4911 - val_loss: 0.6498 - val_accuracy: 0.4240
Epoch 38/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5589 - accuracy: 0.4809 - val_loss: 0.6510 - val_accuracy: 0.4857
Epoch 39/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5556 - accuracy: 0.5451 - val_loss: 0.6689 - val_accuracy: 0.5030
Epoch 40/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5588 - accuracy: 0.4934 - val_loss: 0.6472 - val_accuracy: 0.4277
Epoch 41/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5559 - accuracy: 0.5371 - val_loss: 0.6498 - val_accuracy: 0.4570
Epoch 42/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5552 - accuracy: 0.5316 - val_loss: 0.6526 - val_accuracy: 0.4861
Epoch 43/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5560 - accuracy: 0.4939 - val_loss: 0.6526 - val_accuracy: 0.4537
Epoch 44/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5557 - accuracy: 0.5009 - val_loss: 0.6489 - val_accuracy: 0.5339
Epoch 45/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.4509 - val_loss: 0.6523 - val_accuracy: 0.3961
Epoch 46/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5546 - accuracy: 0.5048 - val_loss: 0.6539 - val_accuracy: 0.4999
Epoch 47/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5551 - accuracy: 0.5060 - val_loss: 0.6521 - val_accuracy: 0.5187
Epoch 48/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5554 - accuracy: 0.4973 - val_loss: 0.6650 - val_accuracy: 0.4844
Epoch 49/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5556 - accuracy: 0.5134 - val_loss: 0.6532 - val_accuracy: 0.5424
Epoch 50/50
751/751 [==============================] - 1s 1ms/step - loss: 0.5550 - accuracy: 0.4812 - val_loss: 0.6540 - val_accuracy: 0.4883

#### Alternative Model 2

In [38]:
# Define the the number of inputs (features) to the model
number_input_features = len(X.iloc[0])

# Review the number of features
number_input_features

101

In [39]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 2

In [40]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 20

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

20

In [41]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [42]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation='relu'))

# Output layer
nn_A2.add(Dense(units=number_output_neurons_A2,activation='linear'))

# Check the structure of the model
# YOUR CODE HERE

In [43]:
# Compile the model
nn_A2.compile(loss='mean_squared_error', optimizer='adam',metrics=['accuracy'])

In [44]:
# Fit the model
fit_model_A2 = nn_A2.fit(X,y,validation_split=0.3, epochs=50)

Epoch 1/50
751/751 [==============================] - 1s 1ms/step - loss: 0.2085 - accuracy: 0.5796 - val_loss: 0.2260 - val_accuracy: 0.5028
Epoch 2/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1913 - accuracy: 0.5532 - val_loss: 0.2251 - val_accuracy: 0.5527
Epoch 3/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1889 - accuracy: 0.5271 - val_loss: 0.2206 - val_accuracy: 0.4656
Epoch 4/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1880 - accuracy: 0.5189 - val_loss: 0.2193 - val_accuracy: 0.5184
Epoch 5/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1877 - accuracy: 0.4969 - val_loss: 0.2196 - val_accuracy: 0.5641
Epoch 6/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1875 - accuracy: 0.4905 - val_loss: 0.2198 - val_accuracy: 0.5338
Epoch 7/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1869 - accuracy: 0.5008 - val_loss: 0.2190 - val_accuracy: 0.5308
Epoch 8/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1868 - accuracy: 0.5017 - val_loss: 0.2199 - val_accuracy: 0.5004
Epoch 9/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1867 - accuracy: 0.4924 - val_loss: 0.2221 - val_accuracy: 0.5274
Epoch 10/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1866 - accuracy: 0.4904 - val_loss: 0.2187 - val_accuracy: 0.4826
Epoch 11/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1866 - accuracy: 0.4940 - val_loss: 0.2193 - val_accuracy: 0.4403
Epoch 12/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1864 - accuracy: 0.4909 - val_loss: 0.2202 - val_accuracy: 0.5290
Epoch 13/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1865 - accuracy: 0.4879 - val_loss: 0.2173 - val_accuracy: 0.5456
Epoch 14/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1862 - accuracy: 0.5048 - val_loss: 0.2175 - val_accuracy: 0.4951
Epoch 15/50
751/751 [==============================] - 1s 2ms/step - loss: 0.1862 - accuracy: 0.4927 - val_loss: 0.2209 - val_accuracy: 0.4642
Epoch 16/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1861 - accuracy: 0.4859 - val_loss: 0.2178 - val_accuracy: 0.4379
Epoch 17/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1861 - accuracy: 0.4877 - val_loss: 0.2206 - val_accuracy: 0.4170
Epoch 18/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1861 - accuracy: 0.5015 - val_loss: 0.2176 - val_accuracy: 0.4573
Epoch 19/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1858 - accuracy: 0.4809 - val_loss: 0.2195 - val_accuracy: 0.5464
Epoch 20/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1860 - accuracy: 0.4952 - val_loss: 0.2194 - val_accuracy: 0.5296
Epoch 21/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1860 - accuracy: 0.4911 - val_loss: 0.2202 - val_accuracy: 0.4100
Epoch 22/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1859 - accuracy: 0.4925 - val_loss: 0.2184 - val_accuracy: 0.5294
Epoch 23/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1858 - accuracy: 0.5067 - val_loss: 0.2192 - val_accuracy: 0.4706
Epoch 24/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1861 - accuracy: 0.5164 - val_loss: 0.2176 - val_accuracy: 0.5378
Epoch 25/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1857 - accuracy: 0.5073 - val_loss: 0.2187 - val_accuracy: 0.4888
Epoch 26/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1858 - accuracy: 0.4935 - val_loss: 0.2194 - val_accuracy: 0.4632
Epoch 27/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1859 - accuracy: 0.5132 - val_loss: 0.2175 - val_accuracy: 0.5689
Epoch 28/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1858 - accuracy: 0.5010 - val_loss: 0.2182 - val_accuracy: 0.5004
Epoch 29/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1858 - accuracy: 0.4946 - val_loss: 0.2185 - val_accuracy: 0.5724
Epoch 30/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1858 - accuracy: 0.4971 - val_loss: 0.2172 - val_accuracy: 0.5337
Epoch 31/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1856 - accuracy: 0.4844 - val_loss: 0.2178 - val_accuracy: 0.4040
Epoch 32/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1858 - accuracy: 0.5152 - val_loss: 0.2209 - val_accuracy: 0.5589
Epoch 33/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1856 - accuracy: 0.4979 - val_loss: 0.2207 - val_accuracy: 0.4115
Epoch 34/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1857 - accuracy: 0.4937 - val_loss: 0.2202 - val_accuracy: 0.5844
Epoch 35/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1859 - accuracy: 0.4891 - val_loss: 0.2193 - val_accuracy: 0.4488
Epoch 36/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1856 - accuracy: 0.4884 - val_loss: 0.2202 - val_accuracy: 0.5397
Epoch 37/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1857 - accuracy: 0.4942 - val_loss: 0.2158 - val_accuracy: 0.6091
Epoch 38/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1856 - accuracy: 0.4946 - val_loss: 0.2193 - val_accuracy: 0.5267
Epoch 39/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1856 - accuracy: 0.4938 - val_loss: 0.2217 - val_accuracy: 0.5350
Epoch 40/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1854 - accuracy: 0.5040 - val_loss: 0.2186 - val_accuracy: 0.4550
Epoch 41/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1855 - accuracy: 0.4966 - val_loss: 0.2199 - val_accuracy: 0.4084
Epoch 42/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1855 - accuracy: 0.5052 - val_loss: 0.2195 - val_accuracy: 0.5148
Epoch 43/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1855 - accuracy: 0.4889 - val_loss: 0.2181 - val_accuracy: 0.5127
Epoch 44/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1855 - accuracy: 0.4904 - val_loss: 0.2179 - val_accuracy: 0.5384
Epoch 45/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1856 - accuracy: 0.5162 - val_loss: 0.2193 - val_accuracy: 0.5356
Epoch 46/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1855 - accuracy: 0.5107 - val_loss: 0.2173 - val_accuracy: 0.5382
Epoch 47/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1853 - accuracy: 0.4961 - val_loss: 0.2177 - val_accuracy: 0.5889
Epoch 48/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1855 - accuracy: 0.5040 - val_loss: 0.2177 - val_accuracy: 0.4569
Epoch 49/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1853 - accuracy: 0.5096 - val_loss: 0.2178 - val_accuracy: 0.4379
Epoch 50/50
751/751 [==============================] - 1s 1ms/step - loss: 0.1854 - accuracy: 0.4853 - val_loss: 0.2177 - val_accuracy: 0.4783

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [45]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X,y)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results

ValueError: in user code:

    File "C:\Users\usezgf00\.conda\envs\dev\lib\site-packages\keras\engine\training.py", line 1366, in test_function  *
        return step_function(self, iterator)
    File "C:\Users\usezgf00\.conda\envs\dev\lib\site-packages\keras\engine\training.py", line 1356, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\usezgf00\.conda\envs\dev\lib\site-packages\keras\engine\training.py", line 1349, in run_step  **
        outputs = model.test_step(data)
    File "C:\Users\usezgf00\.conda\envs\dev\lib\site-packages\keras\engine\training.py", line 1303, in test_step
        y_pred = self(x, training=False)
    File "C:\Users\usezgf00\.conda\envs\dev\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\usezgf00\.conda\envs\dev\lib\site-packages\keras\engine\input_spec.py", line 263, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 107), found shape=(None, 101)

In [47]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =nn_A1.evaluate(X,y)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
1072/1072 [==============================] - 1s 779us/step - loss: 0.5834 - accuracy: 0.4898
Loss: 0.5834126472473145, Accuracy: 0.48981019854545593

In [48]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X,y)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
1072/1072 [==============================] - 1s 742us/step - loss: 0.1951 - accuracy: 0.4846
Loss: 0.19514551758766174, Accuracy: 0.48459139466285706

### Step 3: Save each of your alternative models as an HDF5 file.

In [49]:
# Set the file path for the first alternative model
file_path = Path('Resources/Alphabet_Soup_Alt1.hdf5')

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [50]:
# Set the file path for the second alternative model
file_path =Path('Resources/Alphabet_Soup_Alt2.hdf5')

# Export your model to a HDF5 file
nn_A2.save(file_path)